#!/bin/bash

# shellcheck source=../_helpers/common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/_helpers/common.sh" "$@"

echo ""
echo "Setting up host config"

CONFIG_PATH="$HOME/.dotfiles-config"
CURRENT_HOST="$(scutil --get LocalHostName)"

# Keys prompted and stored generically. host and dotfiles_root are handled
# separately: host is auto-detected, dotfiles_root is always the clone this
# script is running from.
KEYS=(developer_root brew_prefix username bao_cacert)

EXIST_HOST=""
EXIST_KEYS=()
EXIST_VALS=()

# Read ~/.dotfiles-config into EXIST_HOST / EXIST_KEYS / EXIST_VALS.
# bash 3.2 (macOS default) has no associative arrays, so this delegates to
# zsh to source the file and dump its DOTFILES_CONFIG array as tab-separated
# pairs, which bash then parses into parallel indexed arrays.
read_existing_config() {
    local k v
    while IFS=$'\t' read -r k v; do
        [[ -z "$k" ]] && continue
        if [[ "$k" == "host" ]]; then
            EXIST_HOST="$v"
        else
            EXIST_KEYS+=("$k")
            EXIST_VALS+=("$v")
        fi
    done < <(CONFIG_PATH="$CONFIG_PATH" zsh -c '
        source "$CONFIG_PATH"
        for k in ${(ko)DOTFILES_CONFIG}; do
            printf "%s\t%s\n" "$k" "${DOTFILES_CONFIG[$k]}"
        done
    ')
}

get_existing_value() {
    local key="$1" i
    for i in "${!EXIST_KEYS[@]}"; do
        if [[ "${EXIST_KEYS[$i]}" == "$key" ]]; then
            printf '%s' "${EXIST_VALS[$i]}"
            return 0
        fi
    done
    printf ''
}

# Escape a value for a single-quoted zsh literal.
zsh_quote() {
    printf '%s' "$1" | sed "s/'/'\\\\''/g"
}

compute_default() {
    local key="$1" existing
    existing="$(get_existing_value "$key")"
    if [[ -n "$existing" ]]; then
        printf '%s' "$existing"
        return
    fi
    case "$key" in
        developer_root)
            printf '%s' "$HOME/Developer"
            ;;
        brew_prefix)
            if command -v brew &> /dev/null; then
                brew --prefix
            else
                printf '%s' "/opt/homebrew"
            fi
            ;;
        username)
            id -un
            ;;
        bao_cacert)
            printf '%s' ""
            ;;
    esac
}

# Confirm the clone this script is running from as dotfiles_root. There is
# nothing to type here: the value is always $REPO_DIR, since that is the only
# candidate the running invocation could mean.
confirm_dotfiles_root() {
    echo ""
    echo "  Use this directory as your dotfiles root?"
    echo "    $REPO_DIR"
    read -r -p "  (y/n): " REPLY
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "! Re-run this script from the directory you want as your dotfiles root." >&2
        exit 1
    fi
}

write_config() {
    {
        echo "# Generated by hosts/macos_setup.sh"
        echo "# Do not edit, re-run setup to change these values."
        echo "typeset -gA DOTFILES_CONFIG"
        echo "DOTFILES_CONFIG[host]='$(zsh_quote "$CURRENT_HOST")'"
        echo "DOTFILES_CONFIG[dotfiles_root]='$(zsh_quote "$REPO_DIR")'"
        local i
        for i in "${!KEYS[@]}"; do
            echo "DOTFILES_CONFIG[${KEYS[$i]}]='$(zsh_quote "${NEW_VALS[$i]}")'"
        done
    } > "$CONFIG_PATH"
}

if [[ "$NON_INTERACTIVE" == true ]]; then
    if [[ -f "$CONFIG_PATH" ]]; then
        echo "..Using existing config: $CONFIG_PATH"
        exit 0
    else
        echo "! Error: no $CONFIG_PATH found." >&2
        echo "! Run macos_setup.sh interactively once on this machine to create it." >&2
        exit 1
    fi
fi

if [[ -f "$CONFIG_PATH" ]]; then
    read_existing_config

    if [[ -n "$EXIST_HOST" && "$EXIST_HOST" != "$CURRENT_HOST" ]]; then
        echo "! Warning: this config was generated on host '$EXIST_HOST'," >&2
        echo "!          but this machine reports '$CURRENT_HOST'." >&2
    fi

    echo "..Using existing config: $CONFIG_PATH"
    echo ""
    printf "  %-16s %s\n" "dotfiles_root" "$(get_existing_value dotfiles_root)"
    for key in "${KEYS[@]}"; do
        printf "  %-16s %s\n" "$key" "$(get_existing_value "$key")"
    done
    echo ""
    read -r -p "  Keep these values? (y/n): " REPLY
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "..Keeping existing config"
        exit 0
    fi
    echo "..Updating config"
else
    echo "..No existing config found, creating one"
fi

confirm_dotfiles_root

NEW_VALS=()
for key in "${KEYS[@]}"; do
    default="$(compute_default "$key")"
    read -r -p "  $key [$default]: " input
    NEW_VALS+=("${input:-$default}")
done

write_config
echo "..Wrote $CONFIG_PATH"
