# Default Shell
set -g default-shell /bin/zsh

# Active pane
set-option -g pane-active-border-style fg=green

# Dim inactive panes
set -g window-style 'fg=colour245,bg=colour235'
set -g window-active-style 'fg=white,bg=black'
