# Default Shell
set -g default-shell /bin/zsh

# Fix colors
set -g default-terminal "screen-256color"

# Dim inactive panes
set -g window-style 'fg=colour250,bg=colour238'
set -g window-active-style 'fg=white,bg=black'

# Mouse mode
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows when one is closed
set -g renumber-windows on

# Increase scrollback buffer
set -g history-limit 10000

# Don't rename windows automatically
set -g allow-rename off

# Enable activity alerts
setw -g monitor-activity on
set -g visual-activity off

# Easier split commands (| and -)
bind | split-window -h
bind - split-window -v

# Vi mode for copy mode
setw -g mode-keys vi

# Faster command sequences (reduce escape time)
set -s escape-time 0
