#!/bin/bash

export CLICOLOR=1
export LSCOLORS=gabadaeafaabacadaeafag


### Generic Config

ps1() {
    local ps1_string="\[\e[0m\]\[\e[32m\]\W\[\e[0m\] \[\e[94m\]> \[\e[0m\]"

    for param in "$@"; do
        if [ "$param" == "git" ]; then
            ps1_string="\[\e[95m\][\$(git-branch-name 2>/dev/null || echo '-')\[\e[38;5;230m\]|\[\e[95m\]\$(git_status_check 2>/dev/null || echo '-')\[\e[0m\]\[\e[95m\]] \[\e[0m\]$ps1_string"
        fi

        if [ "$param" == "k8s" ]; then
            ps1_string="\[\e[93m\][\$(kubectl config current-context 2>/dev/null || echo '-')\[\e[38;5;230m\]|\[\e[93m\]\$(kubectl config view --minify --output 'jsonpath={..namespace}' 2>/dev/null || echo '-')\[\e[0m\]\[\e[93m\]] \[\e[0m\]$ps1_string"
        fi

        if [ "$param" == "date" ]; then
            ps1_string="\[\e[91m\]\d\[\e[0m\] $ps1_string"
        fi

        if [ "$param" == "host" ]; then
            ps1_string="\[\e[96m\]\h\[\e[0m\] $ps1_string"
        fi

    done


    if [ -n "$VIRTUAL_ENV" ]; then
        ps1_string="\[\e[97m\](\$(basename $VIRTUAL_ENV)) \[\e[0m\]$ps1_string"
    fi

    if [ "$#" -ne 0 ]; then
        export PS1="$ps1_string"
    else
        echo "git, k8s, date, host"
    fi

}


### Homebrew

eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"


### Git and Linting

alias git-branch-name='git rev-parse --abbrev-ref HEAD'
alias git-publish-nolint='git push origin $(git-branch-name)'
alias git-ps1='git_ps1'

git_status_check() {
    if [ -n "$(git status --porcelain 2>/dev/null)" ]
    then
        echo -n "*"
        return 0
    fi
    local current_branch
    current_branch=$(git branch --show-current 2>/dev/null)
    if [ -n "$current_branch" ] && git rev-parse --verify "origin/$current_branch" &>/dev/null; then
        if [ -n "$(git log "origin/$current_branch..HEAD" 2>/dev/null)" ]
        then
            echo -n "!"
            return 0
        fi
    fi
    return 1
}


lint() {
    has_error=0

    if ! command -v tofu &> /dev/null; then
        echo "- Opentofu not found.  Skipping Opentofu linting."
    else
        echo "+ Checking Opentofu"
        if ! tofu fmt -check -recursive; then
            has_error=1
        fi
    fi

    if [[ -n $VIRTUAL_ENV ]]; then
        echo "+ Virtual Env Found.  Checking Python via Black"
        if ! black --check .; then
            has_error=1
        fi
    elif command -v black &> /dev/null; then
        echo "+ Checking Python via Black"
        if ! black --check .; then
            has_error=1
        fi
    else
        echo "- No Virtual Env or Black Found.  Skipping Python linting."
    fi

    if ! command -v golangci-lint &> /dev/null; then
        echo "- Golangci-lint not found.  Skipping golang linting."
    else
        echo "+ Checking Golang"
        repo_root=$(git rev-parse --show-toplevel)
        echo "+ - Starting golangci-lint in directory: $repo_root"
        for file in "$repo_root"/*; do
            if [ -d "$file" ]; then
                for subfile in "$file"/*; do
                    if [ -f "$subfile" ] && [[ "$(basename "$subfile")" == "main.go" ]]; then
                        echo "+ - Go Directory: $file"
                        pushd "$file" > /dev/null || exit
                        golangci-lint run -E bodyclose --timeout 5m0s
                        if ! golangci-lint run -E bodyclose --timeout 5m0s; then
                            has_error=1
                        fi
                        popd > /dev/null || exit
                        break
                    fi
                done
            fi
        done
    fi

    if ! command -v shellcheck &> /dev/null; then
        echo "- Shellcheck not found.  Skipping shell linting."
    else
        echo "+ Checking Shell"
        if ! find . -not -path '*/.git/*' -type f -exec grep -Eq '^#!(.*/|.*env +)(sh|bash|ksh)' {} \; -exec shellcheck {} +; then
            has_error=1
        fi
    fi

    return $has_error
}

alias git-publish='git_publish'
git_publish() {
    if ! lint; then
        echo ":( Linting failed.  Not publishing."
        return 1
    fi

    echo ":) Linting passed.  Publishing."
    echo "   --    ____"
    echo "  ---  /|_||_\`.__"
    echo "   -- (   _    _ _\\"
    git-publish-nolint
}


### Kubernetes


### Vault and OpenBao

alias vault="echo '! using bao !' && bao"
[[ -f "$HOME/.openbao_aliases.sh" ]] && source "$HOME/.openbao_aliases.sh"

# BAO_BINARY_PATH="/opt/homebrew/bin/bao"
# bao() {
#     export BAO_CACERT="/Users/drizzutojr/Developer/Projects/HomeLab/Certs/CA.pem"
#     if [[ "$1" == "local" ]]
#     then
#         shift 1
#         BAO_ADDR="http://127.0.0.1:8200" $BAO_BINARY_PATH "$@"
#     elif [[ "$1" == "dev" ]]
#     then
#         shift 1
#         BAO_ADDR="https://dev.openbao.homelab:8200" $BAO_BINARY_PATH "$@"
#     elif [[ "$1" == "prod" ]]
#     then
#         shift 1
#         BAO_ADDR="https://openbao.homelab:8200" $BAO_BINARY_PATH "$@"
#     else
#         /usr/local/bin/bao "$@"
#     fi
# }

### Terraform

alias terraform="echo '! using tofu !' && tofu"

### Homelab k8s

alias k="kubectl"
alias k-setns="kubectl config set-context --current --namespace"
alias k-dev="export KUBECONFIG=~/.kube/dev.k8s.homelab-config; kubectl"
alias k-prod="export KUBECONFIG=~/.kube/dk8s.homelab-config; kubectl"

### Home Laptop

alias cd-developer="cd /Users/drizzutojr/Developer"
alias cd-homelab="cd /Users/drizzutojr/Developer/Projects/HomeLab"
alias cd-dotfiles="cd /Users/drizzutojr/Developer/Projects/Drizzutojr/dotfiles"

### Developer

developer() {
    badge "Developer"
    ps1 git k8s host
    if [[ "$1" == "-" ]]
    then
        echo "Changing to Developer Directory"
        cd /Users/drizzutojr/Developer || return
        open -g -a "Visual Studio Code" .
    fi
}


### HomeLab

homelab() {
    badge "HomeLab"
    ps1 git k8s host
    if [[ "$1" == "-" ]]
    then
        echo "Changing to HomeLab Directory"
        cd /Users/drizzutojr/Developer/Projects/HomeLab || return
        open -g -a "Visual Studio Code" .
    fi
}

### iTerm2

badge() {
    badgeMessage="$1"
    echo -ne "\033]1337;SetBadgeFormat=$(echo -n "$badgeMessage" | base64)\a"
}


#### Setup
ps1 date
echo "ᕦ (ò_ó *) ᕤ"

# shellcheck disable=SC1091
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"